### ISSUE TITLE
make compilation error

### ISSUE THREAD

**Issue by soumyasanyal** [gjoni/mylddt#1]
While trying to make the c++ code on linux, I'm getting the following error:

**Error**
src/Chain.cpp: In member function ‘std::vector<std::tuple<int, int, double> > Chain::GetContacts(double) const’:
src/Chain.cpp:271:52: error: converting to ‘std::vector<std::tuple<int, int, double> >::value_type {aka std::tuple<int, int, double>}’ from initializer list would use explicit constructor ‘constexpr std::tuple< <template-parameter-1-1> >::tuple(_UElements&& ...) [with _UElements = {int&, int&, double&}; <template-parameter-2-2> = void; _Elements = {int, int, double}]’
     conts.push_back( { A->atomNum, B->atomNum, d } );
                                                    ^
Makefile:24: recipe for target 'obj/Chain.o' failed

**g++ version in Ubuntu:**
g++ (Ubuntu 5.4.0-6ubuntu1~16.04.10) 5.4.0 20160609

Is the code dependent on some specific version of g++? Things run fine on my macbook which has clang installed and thus it's confusing.

**Comment by gjoni** [comment]
Looks like the problem comes from tuple initialization with curly braces which is not supported by older compilers. Changed to make_tuple(...). Should work now.

**Comment by soumyasanyal** [comment]
Thanks, this fixed the issue.
