### ISSUE TITLE
A problem when compiling the source code.

### ISSUE THREAD

**Issue by jcchan23** [gjoni/mylddt#2]
Hello gjoni, I am a user of your program, thanks for your contribution. Here is the problem I met.
After cloing the mylddt program, I entered "make" command and some error happen below.

> g++ -Wall -Wno-unused-result -pedantic -O3 -mtune=native -std=c++11 -g -ggdb -I./src -c -o obj/MyLDDT.o src/MyLDDT.cpp
src/MyLDDT.cpp: In member function ‘std::tuple<double, int, int> MyLDDT::lddt(const Atom&, const Chain&, const Atom&, const Chain&)’:
src/MyLDDT.cpp:290:28: error: converting to ‘std::tuple<double, int, int>’ from initializer list would use explicit constructor ‘constexpr std::tuple< <template-parameter-1-1> >::tuple(_UElements&& ...) [with _UElements = {double&, int&, int&}; <template-parameter-2-2> = void; _Elements = {double, int, int}]’
  return {score, ngood, nmax};

I also followed the step that "if make does not work" and obtained a new error:

> Topology.h:213:1: error: converting to ‘const std::tuple<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >’ from initializer list would use explicit constructor ‘constexpr std::tuple< <template-parameter-1-1> >::tuple(_UElements&& ...) [with _UElements = {const char (&)[3], const char (&)[3], const char (&)[4]}; <template-parameter-2-2> = void; _Elements = {std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >}]’

The g++ version of my machine is "g++ (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609" and I don't know how to solve it, could you please give me some suggestion? I am sorry for my pooling english which may cause some misunderstanding. Thank you!

**Comment by gjoni** [comment]
Hi jcchan23. The reason for the errors is a relatively old compiler version (g++ 5.4.0) which you used. This code needs gcc version 6.1.0 and above.

**Comment by XuanLin1991** [comment]
Hello gjoni, 

Thanks for your sharing, it's an interesting work. And I also met such a problem about gcc compiler on Linux server. Though it can be solved by update the gcc version to 6.1.0 and above, is there any other method to modify the code under the current gcc version? 

My gcc version is Ubuntu 5.4.0-6ubuntu1~16.04.11 5.4.0 20160609.

Best regards,
Xuan Lin
